
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author abdelrhman
 */
public class Menu extends javax.swing.JFrame {

    private int id;
    private int pid = 1;
    PreparedStatement pst0 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;

    private String cust_id = "12";
    private int rest_id = 1;

    private int burger_id = 1;
    private int chicken_id = 2;
    private int cake_id = 3;
    private int donate_id = 4;
    private int tea_id = 5;
    private int greentea_id = 6;
    private int pepsi_id = 7;
    private int mango_id = 8;

    public Menu() {
        initComponents();
        //    jButton1.setEnabled(false);
    }

    public Menu(int rid, String c) {
        rest_id = rid;
        this.cust_id = c;
        initComponents();
        //    jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        friedChicken = new javax.swing.JSpinner();
        Burger = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        greenTea = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tea = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        donates = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cake = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        mango = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pepsi = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(1200, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 293));

        jPanel2.setBackground(java.awt.Color.blue);

        jLabel1.setBackground(java.awt.Color.orange);
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("                        Main Dish ");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Beef Burger         30");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Fried Chicken\t    40");

        friedChicken.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        Burger.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addComponent(friedChicken)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Burger)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Burger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jLabel3.setText("                          Drinks");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(java.awt.Color.gray);

        jLabel2.setText("             Drinks");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );

        jPanel7.setBackground(java.awt.Color.gray);

        jLabel9.setBackground(java.awt.Color.orange);
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("                        Hot Drinks");

        greenTea.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Green Tea    20");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Tea               10");

        tea.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addComponent(greenTea)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tea)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        jPanel8.setBackground(java.awt.Color.lightGray);

        jLabel12.setBackground(java.awt.Color.orange);
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("                        Desserts");

        donates.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Donate                    20");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Cheese Cake     30");

        cake.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(donates)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addComponent(cake)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        jPanel9.setBackground(java.awt.Color.orange);

        jLabel15.setBackground(java.awt.Color.orange);
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("                        Cold Drinks");

        mango.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Mango       35");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Pepsi          15");

        pepsi.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addComponent(mango)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pepsi)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel8.setText("                                            Main Menu");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(452, 452, 452)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection conn = DB_connection.db_connection();
        try {
            String sql0 = "SELECT max(pid) FROM payment ";
            pst0 = DB_connection.db_connection().prepareStatement(sql0);
            ResultSet rs0 = pst0.executeQuery();
            while (rs0.next()) {
                pid = rs0.getInt(1);
                pid++;
            }

            Integer total = 0;
            boolean flag_burger = false;
            boolean flag_chicken = false;
            boolean flag_cake = false;
            boolean flag_donates = false;
            boolean flag_tea = false;
            boolean flag_greenTea = false;
            boolean flag_pepsi = false;
            boolean flag_mango = false;

            //number of each item has been selected
            int num_burger1 = Integer.parseInt(Burger.getValue().toString());
            int num_chicken1 = Integer.parseInt(friedChicken.getValue().toString());
            int num_cake1 = Integer.parseInt(cake.getValue().toString());
            int num_donates1 = Integer.parseInt(donates.getValue().toString());
            int num_tea1 = Integer.parseInt(tea.getValue().toString());
            int num_greenTea1 = Integer.parseInt(greenTea.getValue().toString());
            int num_pepsi1 = Integer.parseInt(pepsi.getValue().toString());
            int num_mango1 = Integer.parseInt(mango.getValue().toString());

            //price of each item 
            int price_burger1 = 30;
            int price_chicken1 = 40;
            int price_cake1 = 30;
            int price_donates1 = 20;
            int price_tea1 = 10;
            int price_greenTea1 = 20;
            int price_pepsi1 = 15;
            int price_mango1 = 35;

            //total price of eah item 
            int price_tot_burger1 = price_burger1 * num_burger1;
            int price_tot_chicken1 = price_chicken1 * num_chicken1;
            int price_tot_cake1 = price_cake1 * num_cake1;
            int price_tot_donates1 = price_donates1 * num_donates1;
            int price_tot_tea1 = price_tea1 * num_tea1;
            int price_tot_greenTea1 = price_greenTea1 * num_greenTea1;
            int price_tot_pepsi1 = price_pepsi1 * num_pepsi1;
            int price_tot_mango1 = price_mango1 * num_mango1;
            total = price_tot_burger1 + price_tot_chicken1 + price_tot_cake1 + price_tot_donates1 + price_tot_tea1 + price_tot_greenTea1 + price_tot_pepsi1 + price_tot_mango1;

            String sql3 = "insert into payment(pid,total_payment)  values (?,?)";
            //  String sql2 = "SELECT cid FROM customer  ";   
            pst2 = DB_connection.db_connection().prepareStatement(sql3);
            pst2.setInt(1, pid);
            pst2.setInt(2, total);
            if (pst2.executeUpdate() > 0) {
                System.err.println("added in payment table");
            } else {
                System.err.println("cannot add in payment table");
            }

            if (!(price_tot_burger1 == 0)) {

                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }

                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";

                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);

                pst.setInt(1, id);
                pst.setInt(2, num_burger1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, burger_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_burger = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_chicken1 == 0)) {

                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);

                pst.setInt(1, id);
                pst.setInt(2, num_chicken1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, chicken_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_chicken = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_cake1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";
                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                pst.setInt(1, id);
                pst.setInt(2, num_cake1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, cake_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_cake = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_donates1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                pst.setInt(1, id);
                pst.setInt(2, num_donates1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, donate_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_donates = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_tea1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                pst.setInt(1, id);
                pst.setInt(2, num_tea1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, tea_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_tea = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_greenTea1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                pst.setInt(1, id);
                pst.setInt(2, num_greenTea1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, greentea_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_greenTea = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_mango1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                pst.setInt(1, id);
                pst.setInt(2, num_mango1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, mango_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_mango = true;
                } else {

                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (!(price_tot_pepsi1 == 0)) {
                String sql1 = "SELECT max(oid) FROM orders ";
                pst1 = DB_connection.db_connection().prepareStatement(sql1);
                ResultSet rs = pst1.executeQuery();
                while (rs.next()) {
                    id = rs.getInt(1);
                    id++;
                }
                //insert in the orders table
                String sql = "insert into orders(oid,number_of_units,cid,rid,iid,pid)  values (?,?,?,?,?,?)";                //  String sql2 = "SELECT cid FROM customer  ";   
                pst = DB_connection.db_connection().prepareStatement(sql);
                pst.setInt(1, id);
                pst.setInt(2, num_pepsi1);
                pst.setString(3, cust_id);
                pst.setInt(4, rest_id);
                pst.setInt(5, pepsi_id);
                pst.setInt(6, pid);

                if (pst.executeUpdate() > 0) {
                    flag_pepsi = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to Add user");
                }
            }
            if (flag_burger || flag_chicken || flag_cake || flag_donates || flag_tea || flag_greenTea || flag_pepsi || flag_mango) {

                payment p = new payment(rest_id, total, cust_id);
                p.setVisible(true);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "please select an item ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Burger;
    private javax.swing.JSpinner cake;
    private javax.swing.JSpinner donates;
    private javax.swing.JSpinner friedChicken;
    private javax.swing.JSpinner greenTea;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner mango;
    private javax.swing.JSpinner pepsi;
    private javax.swing.JSpinner tea;
    // End of variables declaration//GEN-END:variables
}
