
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Media;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author abdelrhman
 */
public class RORS_customer_signup extends javax.swing.JFrame {

    PreparedStatement pst = null;

    public RORS_customer_signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invalid_password = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sign_up_phone = new javax.swing.JTextField();
        sign_up_email = new javax.swing.JTextField();
        sign_up_name = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        sign_up_password = new javax.swing.JPasswordField();
        invalid_email = new javax.swing.JLabel();
        invalid_password1 = new javax.swing.JLabel();
        invalid_username = new javax.swing.JLabel();
        invalid_phone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setSize(new java.awt.Dimension(500, 400));

        invalid_password.setBackground(java.awt.Color.darkGray);

        jPanel2.setBackground(java.awt.Color.orange);

        jLabel1.setFont(new java.awt.Font("Umpush", 1, 36)); // NOI18N
        jLabel1.setText("SignUp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("UserName");

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Email");

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Password");

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("phone");

        sign_up_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_phoneActionPerformed(evt);
            }
        });

        sign_up_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_emailActionPerformed(evt);
            }
        });

        sign_up_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_nameActionPerformed(evt);
            }
        });

        signup.setText("Submit");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        invalid_email.setBackground(java.awt.Color.magenta);
        invalid_email.setForeground(java.awt.Color.red);

        invalid_password1.setForeground(java.awt.Color.red);

        invalid_username.setForeground(java.awt.Color.red);

        invalid_phone.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout invalid_passwordLayout = new javax.swing.GroupLayout(invalid_password);
        invalid_password.setLayout(invalid_passwordLayout);
        invalid_passwordLayout.setHorizontalGroup(
            invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(invalid_passwordLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(invalid_passwordLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invalid_passwordLayout.createSequentialGroup()
                        .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sign_up_phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(sign_up_email)
                            .addComponent(sign_up_password)
                            .addComponent(sign_up_name, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(invalid_passwordLayout.createSequentialGroup()
                        .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invalid_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invalid_email, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invalid_username, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invalid_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        invalid_passwordLayout.setVerticalGroup(
            invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invalid_passwordLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign_up_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(invalid_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign_up_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalid_password1)
                .addGap(1, 1, 1)
                .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_up_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(invalid_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invalid_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_up_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalid_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(invalid_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invalid_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sign_up_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_up_phoneActionPerformed

    private void sign_up_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_up_emailActionPerformed

    private void sign_up_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_up_nameActionPerformed
    class email_check1 {

        String part1, part2;

        String email = sign_up_email.getText().strip();

        public String check() {
            try {

                if ((email.indexOf('@') == -1)) {
                    throw new Exception("Invalid Email !!");
                } else {
                    StringTokenizer em = new StringTokenizer(email, "@");
                    if (em.hasMoreTokens()) {
                        part1 = em.nextToken();
                    } else {
                        throw new Exception("Invalid Email !!");
                    }
                    if (em.hasMoreTokens()) {
                        part2 = em.nextToken();
                    } else {
                        throw new Exception("Invalid Email !!");
                    }

                    if (!(part2.endsWith(".com")) || (part1.length() < 8)) {
                        throw new Exception("Invalid Email");

                    }
                }
            } catch (Exception e) {
                invalid_email.setText("invalid Email");
                return "Error";
            }
            return email;
        }

    }

    class phone_check1 {

        String phone = sign_up_phone.getText().strip();
        ArrayList<Character> arr = new ArrayList<Character>();

        public String check() {
            try {

                if ((phone.isEmpty())) {
                    throw new Exception("Invalid phone number!!");
                } else if (!(phone.length() == 11)) {
                    throw new Exception("Invalid phone number!!");
                } else {

                    for (int i = 0; i < phone.length(); i++) {
                        arr.add(phone.charAt(i));
                        if (Character.isLetter(arr.get(i))) {
                            throw new Exception("Invalid phone number  !!");
                        }
                    }
                }
            } catch (Exception e) {

                invalid_phone.setText(("invalid Phone Number "));
                return "Error";
            }
            return phone;
        }

    }


    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        try {

            Connection conn = DB_connection.db_connection();
            email_check1 c = new email_check1();
            String email = c.check();
            if (email.equals("Error")) {
                throw new Exception();
            }
            String username = sign_up_name.getText().strip();
            String password = sign_up_password.getText().strip();
            phone_check1 p = new phone_check1();
            String phone = p.check();
            if(password.isEmpty() || password.length() < 8){
                throw new Exception();
            }
            if (phone.equals("Error")) {
                throw new Exception();
            }
            String sql = "insert into customer  values (?,?,?,?,?)";
            pst = DB_connection.db_connection().prepareStatement(sql);

            pst.setString(1, phone);
            pst.setString(2, username);
            pst.setString(3, phone);
            pst.setString(4, email);
            pst.setString(5, password);

            if (pst.executeUpdate() > 0) {
       
                invalid_email.setText("");
                invalid_phone.setText("");
                JOptionPane.showMessageDialog(null, "Done");
                RORS_customer_login login = new RORS_customer_login();
              
                login.setVisible(true);
                this.setVisible(false);
            } else {
                sign_up_name.setText("");
                sign_up_email.setText("");
                sign_up_phone.setText("");
                sign_up_password.setText("");

                JOptionPane.showMessageDialog(null, "Failed to Add user");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
            sign_up_name.setText("");
            sign_up_email.setText("");
            sign_up_phone.setText("");
            sign_up_password.setText("");

        }


    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RORS_customer_signup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RORS_customer_signup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RORS_customer_signup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RORS_customer_signup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RORS_customer_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invalid_email;
    private javax.swing.JPanel invalid_password;
    private javax.swing.JLabel invalid_password1;
    private javax.swing.JLabel invalid_phone;
    private javax.swing.JLabel invalid_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField sign_up_email;
    private javax.swing.JTextField sign_up_name;
    private javax.swing.JPasswordField sign_up_password;
    private javax.swing.JTextField sign_up_phone;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
